name: lint me.md

on:
  push:
    paths:
      - "**/*.md"
      - "schema/**"
      - "src/**"
      - "bin/**"
      - "package.json"
  pull_request:
    paths:
      - "**/*.md"
      - "schema/**"
      - "src/**"
      - "bin/**"
      - "package.json"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
      - run: npm install
      - run: node bin/me-md.js lint me.md
      - run: node bin/me-md.js lint examples/minimal.me.md
      - run: node bin/me-md.js lint examples/cunningfolk.me.md
